def BYE():

    import time

    print()
    print()
    time.sleep(.10)
    print("                                       ")
    time.sleep(.10)
    print("   ▄▄▀▀▀▀▀▄                            ")
    time.sleep(.10)
    print("  ▄▀       ▀▄                          ")
    time.sleep(.10)
    print(" ▄▀   ▄▄    ▀▀▀▀▀▀▀▄▄▀▀▀▀▀▀▀▀▀▀▀▀▄▄    ")
    time.sleep(.10)
    print(" █    ██                           ▀▄  ")
    time.sleep(.10)
    print(" █    ██▄████▄ ██▄    ▄██ ▄████▄    ▀▄ ")
    time.sleep(.10)
    print(" █    ██▀  ▀██▄ ██▄  ██▀ ██▀ ▄██     █ ")
    time.sleep(.10)
    print(" █    ██    ███  █████▀  ██▄█▀▀      █ ")
    time.sleep(.10)
    print(" █    ███▄▄███▀   ▀██▀   ▀██▄▄▄██    █ ")
    time.sleep(.10)
    print(" ▀▄    ▀▀▀▀▀▀     ██▀      ▀▀▀▀▀     █ ")
    time.sleep(.10)
    print("  ▀▄             ██▀   ▄▄         ▄▄▀  ")
    time.sleep(.10)
    print("    ▀▀▀▀▀▀▀▀▀▄   ▀▀   ▄▀ ▀▀▀▀▀▀▀▀▀     ")
    time.sleep(.10)
    print("             ▀▄      ▄▀                ")
    time.sleep(.10)
    print("               ▀▀▀▀▀▀                  ")
    time.sleep(.10)
    print()
    print()
    
