import time

def welcome():
    print()
    time.sleep(.4)
    print("          ────────────────────────▄▀█▀█▀▄")
    time.sleep(.4)
    print("          ───────────────────────▀▀▀▀▀▀▀▀▀")
    time.sleep(.4)
    print("          ────────█──────────────▄─░░░░░▄")
    time.sleep(.4)
    print("          ▄─█────▐▌▌───█──▄─▄───▐▌▌░░░░░▌▌")
    time.sleep(.4)
    print("          █▐▐▌█▌▌█▌█▌▄█▐▌▐█▐▐▌█▌█▌█░░░░░▌▌")
    time.sleep(.4)
    print("          █▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█")
    time.sleep(.4)
    print("          █ █   █ █▀▀ █   █▀▀ █▀▀█ █▀▄▀█ █▀▀ █")
    time.sleep(.4)
    print("          █ █▄█▄█ █▀▀ █   █   █  █ █ ▀ █ █▀▀ █")
    time.sleep(.4)
    print("          █  ▀ ▀  ▀▀▀ ▀▀▀ ▀▀▀ ▀▀▀▀ ▀   ▀ ▀▀▀ █")
    time.sleep(.4)
    print("          ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀")
    time.sleep(.4)
